version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:3.5.6
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka:2.3.0
    environment:
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
    ports:
      - 9092:9092
      - 9093:9093
    depends_on:
      - zookeeper

  kafka-console-consumer:
    image: bitnami/kafka:2.3.0
    entrypoint: kafka-console-consumer.sh --from-beginning

  postgres:
    image: postgres:10.7-alpine
    restart: always
    environment:
      POSTGRES_DB: site_check
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
